name: goo_store_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  dio: ^5.1.1
  flutter_secure_storage: ^8.0.0
  get_it: ^7.3.0
  flutter_native_splash: ^2.2.19
  flutter_screenutil: ^5.7.0
  image_picker: ^0.8.7+4
  meta: ^1.8.0
  loading_animation_widget: ^1.2.0+4
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.1.0
  webview_flutter: ^4.2.0
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter_local_notifications: ^14.0.0+1
  freezed: ^2.3.4
  json_annotation: ^4.8.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/images/
 
